project_id = "wysikbsjalfvjwqzkihj"

[functions.admin-search-users]
verify_jwt = true

[functions.admin-cancel-user-subscriptions]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.analyze-video]
verify_jwt = true

[functions.initialize-owner]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-subscription-feedback]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.get-rankings]
verify_jwt = true

[functions.get-owner-profile]
verify_jwt = false

[functions.send-follow-request]
verify_jwt = true

[functions.respond-to-follow]
verify_jwt = true

[functions.download-scout-file]
verify_jwt = true

[functions.search-players]
verify_jwt = true

[functions.get-following-players]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-module-subscription]
verify_jwt = true

[functions.cancel-all-subscriptions]
verify_jwt = true

[functions.resume-module-subscription]
verify_jwt = true
